# 数据库配置
database:
  driver: "mysql"       # 数据库驱动（mysql、postgres 等）
  host: "localhost"     # 地址
  port: 3306            # 端口
  username: "root"      # 用户名
  password: "password"    # 密码
  dbname: "xz"     # 数据库名
  charset: "utf8mb4"    # 字符集
#服务器发现注册配置
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone: http://admin:admin@localhost:9000/eureka/
# 日志配置
log:
  path: "../logs/app.log"  # 日志文件路径（与 src 同级的 logs 目录）
  level: "info"           # 日志级别（debug/info/warn/error）
  format: "text"          # 日志格式（text/json）
  max_size: 10            # 单个文件最大大小（MB，可选，用于切割）
aseKey:
  key: "yangzhixuan944166810@qq.com1150614966@qq.com13735713859" # 对称加密密钥（需安全存储，如配置中心）
file:
  upload-baseUrl: "file-storage" # 文件下载基础 URL
  max-file-size: 200
  max-chunk-size: 5
minio:
  endpoint: 192.168.56.129:19000       # MinIO服务地址（本地部署的话默认9000）
  access-key-id: minio      # 你的MinIO AccessKey
  secret-access-key: QWEasd123  # 你的MinIO SecretKey
  bucket-name: imbucket          # 桶名（和你测试代码里的imbucket一致）
  use-ssl: false                 # 本地测试一般关闭SSL
  redis-prefix: "minio_core_upload:" # Redis 元数据前缀（必填）
  expire-time: 168h                # 元数据过期时间（7天）
  chunk-size: 5         # 单分片大小（mb）
  max-file-size: 200     # 最大文件大小（mb）
redis:
  host: localhost
  port: 6379
  password:
retry:
  max-retries: 3                   # 重试次数
  retry-delay: 100ms               # 重试间隔
