// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.8
// source: proto/filestorage/fileStorage.proto

package filestorage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileStorageService_UploadFile_FullMethodName            = "/filestorage.FileStorageService/UploadFile"
	FileStorageService_UploadFileFromUrl_FullMethodName     = "/filestorage.FileStorageService/UploadFileFromUrl"
	FileStorageService_GetFileDetail_FullMethodName         = "/filestorage.FileStorageService/GetFileDetail"
	FileStorageService_UploadFileChunked_FullMethodName     = "/filestorage.FileStorageService/UploadFileChunked"
	FileStorageService_CompleteChunkedUpload_FullMethodName = "/filestorage.FileStorageService/CompleteChunkedUpload"
)

// FileStorageServiceClient is the client API for FileStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 文件存储服务
type FileStorageServiceClient interface {
	// 上传文件（流式传输，支持大文件）
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFileRequest, UploadFileResponse], error)
	// 从URL上传文件
	UploadFileFromUrl(ctx context.Context, in *UploadFileFromUrlRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
	// 获取文件详情
	GetFileDetail(ctx context.Context, in *GetFileDetailRequest, opts ...grpc.CallOption) (*FileDetailResponse, error)
	// 新的分片上传接口
	UploadFileChunked(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, UploadFileResponse], error)
	CompleteChunkedUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
}

type fileStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileStorageServiceClient(cc grpc.ClientConnInterface) FileStorageServiceClient {
	return &fileStorageServiceClient{cc}
}

func (c *fileStorageServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFileRequest, UploadFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileStorageService_ServiceDesc.Streams[0], FileStorageService_UploadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadFileRequest, UploadFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileStorageService_UploadFileClient = grpc.ClientStreamingClient[UploadFileRequest, UploadFileResponse]

func (c *fileStorageServiceClient) UploadFileFromUrl(ctx context.Context, in *UploadFileFromUrlRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileResponse)
	err := c.cc.Invoke(ctx, FileStorageService_UploadFileFromUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileStorageServiceClient) GetFileDetail(ctx context.Context, in *GetFileDetailRequest, opts ...grpc.CallOption) (*FileDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileDetailResponse)
	err := c.cc.Invoke(ctx, FileStorageService_GetFileDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileStorageServiceClient) UploadFileChunked(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, UploadFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileStorageService_ServiceDesc.Streams[1], FileStorageService_UploadFileChunked_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, UploadFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileStorageService_UploadFileChunkedClient = grpc.ClientStreamingClient[FileChunk, UploadFileResponse]

func (c *fileStorageServiceClient) CompleteChunkedUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileResponse)
	err := c.cc.Invoke(ctx, FileStorageService_CompleteChunkedUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileStorageServiceServer is the server API for FileStorageService service.
// All implementations must embed UnimplementedFileStorageServiceServer
// for forward compatibility.
//
// 文件存储服务
type FileStorageServiceServer interface {
	// 上传文件（流式传输，支持大文件）
	UploadFile(grpc.ClientStreamingServer[UploadFileRequest, UploadFileResponse]) error
	// 从URL上传文件
	UploadFileFromUrl(context.Context, *UploadFileFromUrlRequest) (*UploadFileResponse, error)
	// 获取文件详情
	GetFileDetail(context.Context, *GetFileDetailRequest) (*FileDetailResponse, error)
	// 新的分片上传接口
	UploadFileChunked(grpc.ClientStreamingServer[FileChunk, UploadFileResponse]) error
	CompleteChunkedUpload(context.Context, *CompleteUploadRequest) (*UploadFileResponse, error)
	mustEmbedUnimplementedFileStorageServiceServer()
}

// UnimplementedFileStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileStorageServiceServer struct{}

func (UnimplementedFileStorageServiceServer) UploadFile(grpc.ClientStreamingServer[UploadFileRequest, UploadFileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedFileStorageServiceServer) UploadFileFromUrl(context.Context, *UploadFileFromUrlRequest) (*UploadFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadFileFromUrl not implemented")
}
func (UnimplementedFileStorageServiceServer) GetFileDetail(context.Context, *GetFileDetailRequest) (*FileDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileDetail not implemented")
}
func (UnimplementedFileStorageServiceServer) UploadFileChunked(grpc.ClientStreamingServer[FileChunk, UploadFileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadFileChunked not implemented")
}
func (UnimplementedFileStorageServiceServer) CompleteChunkedUpload(context.Context, *CompleteUploadRequest) (*UploadFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteChunkedUpload not implemented")
}
func (UnimplementedFileStorageServiceServer) mustEmbedUnimplementedFileStorageServiceServer() {}
func (UnimplementedFileStorageServiceServer) testEmbeddedByValue()                            {}

// UnsafeFileStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileStorageServiceServer will
// result in compilation errors.
type UnsafeFileStorageServiceServer interface {
	mustEmbedUnimplementedFileStorageServiceServer()
}

func RegisterFileStorageServiceServer(s grpc.ServiceRegistrar, srv FileStorageServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileStorageService_ServiceDesc, srv)
}

func _FileStorageService_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileStorageServiceServer).UploadFile(&grpc.GenericServerStream[UploadFileRequest, UploadFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileStorageService_UploadFileServer = grpc.ClientStreamingServer[UploadFileRequest, UploadFileResponse]

func _FileStorageService_UploadFileFromUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileFromUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileStorageServiceServer).UploadFileFromUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileStorageService_UploadFileFromUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileStorageServiceServer).UploadFileFromUrl(ctx, req.(*UploadFileFromUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileStorageService_GetFileDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileStorageServiceServer).GetFileDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileStorageService_GetFileDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileStorageServiceServer).GetFileDetail(ctx, req.(*GetFileDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileStorageService_UploadFileChunked_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileStorageServiceServer).UploadFileChunked(&grpc.GenericServerStream[FileChunk, UploadFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileStorageService_UploadFileChunkedServer = grpc.ClientStreamingServer[FileChunk, UploadFileResponse]

func _FileStorageService_CompleteChunkedUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileStorageServiceServer).CompleteChunkedUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileStorageService_CompleteChunkedUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileStorageServiceServer).CompleteChunkedUpload(ctx, req.(*CompleteUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileStorageService_ServiceDesc is the grpc.ServiceDesc for FileStorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileStorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "filestorage.FileStorageService",
	HandlerType: (*FileStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadFileFromUrl",
			Handler:    _FileStorageService_UploadFileFromUrl_Handler,
		},
		{
			MethodName: "GetFileDetail",
			Handler:    _FileStorageService_GetFileDetail_Handler,
		},
		{
			MethodName: "CompleteChunkedUpload",
			Handler:    _FileStorageService_CompleteChunkedUpload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _FileStorageService_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadFileChunked",
			Handler:       _FileStorageService_UploadFileChunked_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/filestorage/fileStorage.proto",
}
