// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.8
// source: proto/filestorage/fileStorage.proto

package filestorage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 上传文件请求（流式）- 保持兼容
type UploadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadFileRequest_Metadata
	//	*UploadFileRequest_Chunk
	Data          isUploadFileRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_proto_filestorage_fileStorage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filestorage_fileStorage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_filestorage_fileStorage_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequest) GetData() isUploadFileRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadFileRequest) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Data.(*UploadFileRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadFileRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadFileRequest_Data interface {
	isUploadFileRequest_Data()
}

type UploadFileRequest_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadFileRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadFileRequest_Metadata) isUploadFileRequest_Data() {}

func (*UploadFileRequest_Chunk) isUploadFileRequest_Data() {}

// 新的分片上传消息
type FileChunk struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UploadId       string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`                     // 上传会话ID
	ChunkIndex     int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`              // 分片索引
	TotalChunks    int32                  `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`           // 总分片数
	Data           []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                                             // 分片数据
	FileName       string                 `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                     // 文件名（第一个分片携带）
	MimeType       string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`                     // MIME类型
	FileSystemType string                 `protobuf:"bytes,7,opt,name=file_system_type,json=fileSystemType,proto3" json:"file_system_type,omitempty"` // 文件系统类型
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_filestorage_fileStorage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filestorage_fileStorage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_filestorage_fileStorage_proto_rawDescGZIP(), []int{1}
}

func (x *FileChunk) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *FileChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *FileChunk) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileChunk) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileChunk) GetFileSystemType() string {
	if x != nil {
		return x.FileSystemType
	}
	return ""
}

type CompleteUploadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UploadId       string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	FileName       string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType       string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileSystemType string                 `protobuf:"bytes,4,opt,name=file_system_type,json=fileSystemType,proto3" json:"file_system_type,omitempty"`
	FileHash       string                 `protobuf:"bytes,5,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"` // 最终文件哈希（可选校验）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompleteUploadRequest) Reset() {
	*x = CompleteUploadRequest{}
	mi := &file_proto_filestorage_fileStorage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadRequest) ProtoMessage() {}

func (x *CompleteUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filestorage_fileStorage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_filestorage_fileStorage_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CompleteUploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CompleteUploadRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *CompleteUploadRequest) GetFileSystemType() string {
	if x != nil {
		return x.FileSystemType
	}
	return ""
}

func (x *CompleteUploadRequest) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

// 文件元数据
type FileMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FileSystemType string                 `protobuf:"bytes,1,opt,name=file_system_type,json=fileSystemType,proto3" json:"file_system_type,omitempty"`
	FileName       string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType       string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileSize       int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_proto_filestorage_fileStorage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filestorage_fileStorage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_proto_filestorage_fileStorage_proto_rawDescGZIP(), []int{3}
}

func (x *FileMetadata) GetFileSystemType() string {
	if x != nil {
		return x.FileSystemType
	}
	return ""
}

func (x *FileMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileMetadata) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileMetadata) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

// 从URL上传文件请求
type UploadFileFromUrlRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FileSystemType string                 `protobuf:"bytes,1,opt,name=file_system_type,json=fileSystemType,proto3" json:"file_system_type,omitempty"`
	DownloadUrl    string                 `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	MimeType       string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileName       string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadFileFromUrlRequest) Reset() {
	*x = UploadFileFromUrlRequest{}
	mi := &file_proto_filestorage_fileStorage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileFromUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileFromUrlRequest) ProtoMessage() {}

func (x *UploadFileFromUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filestorage_fileStorage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileFromUrlRequest.ProtoReflect.Descriptor instead.
func (*UploadFileFromUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_filestorage_fileStorage_proto_rawDescGZIP(), []int{4}
}

func (x *UploadFileFromUrlRequest) GetFileSystemType() string {
	if x != nil {
		return x.FileSystemType
	}
	return ""
}

func (x *UploadFileFromUrlRequest) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *UploadFileFromUrlRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *UploadFileFromUrlRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

// 获取文件详情请求
type GetFileDetailRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FileHash       string                 `protobuf:"bytes,1,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	FileSystemType string                 `protobuf:"bytes,2,opt,name=file_system_type,json=fileSystemType,proto3" json:"file_system_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFileDetailRequest) Reset() {
	*x = GetFileDetailRequest{}
	mi := &file_proto_filestorage_fileStorage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileDetailRequest) ProtoMessage() {}

func (x *GetFileDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filestorage_fileStorage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileDetailRequest.ProtoReflect.Descriptor instead.
func (*GetFileDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_filestorage_fileStorage_proto_rawDescGZIP(), []int{5}
}

func (x *GetFileDetailRequest) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *GetFileDetailRequest) GetFileSystemType() string {
	if x != nil {
		return x.FileSystemType
	}
	return ""
}

// 文件详情响应
type FileDetailResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FileName       string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType       string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FileHash       string                 `protobuf:"bytes,4,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	FilePath       string                 `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileSize       int64                  `protobuf:"varint,6,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Uploader       int64                  `protobuf:"varint,7,opt,name=uploader,proto3" json:"uploader,omitempty"`
	FileSystemType string                 `protobuf:"bytes,8,opt,name=file_system_type,json=fileSystemType,proto3" json:"file_system_type,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileDetailResponse) Reset() {
	*x = FileDetailResponse{}
	mi := &file_proto_filestorage_fileStorage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDetailResponse) ProtoMessage() {}

func (x *FileDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filestorage_fileStorage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDetailResponse.ProtoReflect.Descriptor instead.
func (*FileDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_filestorage_fileStorage_proto_rawDescGZIP(), []int{6}
}

func (x *FileDetailResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileDetailResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileDetailResponse) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *FileDetailResponse) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *FileDetailResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileDetailResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileDetailResponse) GetUploader() int64 {
	if x != nil {
		return x.Uploader
	}
	return 0
}

func (x *FileDetailResponse) GetFileSystemType() string {
	if x != nil {
		return x.FileSystemType
	}
	return ""
}

func (x *FileDetailResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *FileDetailResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 上传文件响应
type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FileDetail    *FileDetailResponse    `protobuf:"bytes,3,opt,name=file_detail,json=fileDetail,proto3" json:"file_detail,omitempty"`
	UploadId      string                 `protobuf:"bytes,4,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"` // 返回上传ID用于分片上传
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_proto_filestorage_fileStorage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filestorage_fileStorage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_filestorage_fileStorage_proto_rawDescGZIP(), []int{7}
}

func (x *UploadFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadFileResponse) GetFileDetail() *FileDetailResponse {
	if x != nil {
		return x.FileDetail
	}
	return nil
}

func (x *UploadFileResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

var File_proto_filestorage_fileStorage_proto protoreflect.FileDescriptor

const file_proto_filestorage_fileStorage_proto_rawDesc = "" +
	"\n" +
	"#proto/filestorage/fileStorage.proto\x12\vfilestorage\"l\n" +
	"\x11UploadFileRequest\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x19.filestorage.FileMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"\xe4\x01\n" +
	"\tFileChunk\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x05R\vtotalChunks\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1b\n" +
	"\tfile_name\x18\x05 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12(\n" +
	"\x10file_system_type\x18\a \x01(\tR\x0efileSystemType\"\xb5\x01\n" +
	"\x15CompleteUploadRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12(\n" +
	"\x10file_system_type\x18\x04 \x01(\tR\x0efileSystemType\x12\x1b\n" +
	"\tfile_hash\x18\x05 \x01(\tR\bfileHash\"\x8f\x01\n" +
	"\fFileMetadata\x12(\n" +
	"\x10file_system_type\x18\x01 \x01(\tR\x0efileSystemType\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\"\xa1\x01\n" +
	"\x18UploadFileFromUrlRequest\x12(\n" +
	"\x10file_system_type\x18\x01 \x01(\tR\x0efileSystemType\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\"]\n" +
	"\x14GetFileDetailRequest\x12\x1b\n" +
	"\tfile_hash\x18\x01 \x01(\tR\bfileHash\x12(\n" +
	"\x10file_system_type\x18\x02 \x01(\tR\x0efileSystemType\"\xb9\x02\n" +
	"\x12FileDetailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\x12\x1b\n" +
	"\tfile_hash\x18\x04 \x01(\tR\bfileHash\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_size\x18\x06 \x01(\x03R\bfileSize\x12\x1a\n" +
	"\buploader\x18\a \x01(\x03R\buploader\x12(\n" +
	"\x10file_system_type\x18\b \x01(\tR\x0efileSystemType\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xa7\x01\n" +
	"\x12UploadFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12@\n" +
	"\vfile_detail\x18\x03 \x01(\v2\x1f.filestorage.FileDetailResponseR\n" +
	"fileDetail\x12\x1b\n" +
	"\tupload_id\x18\x04 \x01(\tR\buploadId2\xc5\x03\n" +
	"\x12FileStorageService\x12O\n" +
	"\n" +
	"UploadFile\x12\x1e.filestorage.UploadFileRequest\x1a\x1f.filestorage.UploadFileResponse(\x01\x12[\n" +
	"\x11UploadFileFromUrl\x12%.filestorage.UploadFileFromUrlRequest\x1a\x1f.filestorage.UploadFileResponse\x12S\n" +
	"\rGetFileDetail\x12!.filestorage.GetFileDetailRequest\x1a\x1f.filestorage.FileDetailResponse\x12N\n" +
	"\x11UploadFileChunked\x12\x16.filestorage.FileChunk\x1a\x1f.filestorage.UploadFileResponse(\x01\x12\\\n" +
	"\x15CompleteChunkedUpload\x12\".filestorage.CompleteUploadRequest\x1a\x1f.filestorage.UploadFileResponseB\x1cZ\x1alocal/im/proto/filestorageb\x06proto3"

var (
	file_proto_filestorage_fileStorage_proto_rawDescOnce sync.Once
	file_proto_filestorage_fileStorage_proto_rawDescData []byte
)

func file_proto_filestorage_fileStorage_proto_rawDescGZIP() []byte {
	file_proto_filestorage_fileStorage_proto_rawDescOnce.Do(func() {
		file_proto_filestorage_fileStorage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_filestorage_fileStorage_proto_rawDesc), len(file_proto_filestorage_fileStorage_proto_rawDesc)))
	})
	return file_proto_filestorage_fileStorage_proto_rawDescData
}

var file_proto_filestorage_fileStorage_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_filestorage_fileStorage_proto_goTypes = []any{
	(*UploadFileRequest)(nil),        // 0: filestorage.UploadFileRequest
	(*FileChunk)(nil),                // 1: filestorage.FileChunk
	(*CompleteUploadRequest)(nil),    // 2: filestorage.CompleteUploadRequest
	(*FileMetadata)(nil),             // 3: filestorage.FileMetadata
	(*UploadFileFromUrlRequest)(nil), // 4: filestorage.UploadFileFromUrlRequest
	(*GetFileDetailRequest)(nil),     // 5: filestorage.GetFileDetailRequest
	(*FileDetailResponse)(nil),       // 6: filestorage.FileDetailResponse
	(*UploadFileResponse)(nil),       // 7: filestorage.UploadFileResponse
}
var file_proto_filestorage_fileStorage_proto_depIdxs = []int32{
	3, // 0: filestorage.UploadFileRequest.metadata:type_name -> filestorage.FileMetadata
	6, // 1: filestorage.UploadFileResponse.file_detail:type_name -> filestorage.FileDetailResponse
	0, // 2: filestorage.FileStorageService.UploadFile:input_type -> filestorage.UploadFileRequest
	4, // 3: filestorage.FileStorageService.UploadFileFromUrl:input_type -> filestorage.UploadFileFromUrlRequest
	5, // 4: filestorage.FileStorageService.GetFileDetail:input_type -> filestorage.GetFileDetailRequest
	1, // 5: filestorage.FileStorageService.UploadFileChunked:input_type -> filestorage.FileChunk
	2, // 6: filestorage.FileStorageService.CompleteChunkedUpload:input_type -> filestorage.CompleteUploadRequest
	7, // 7: filestorage.FileStorageService.UploadFile:output_type -> filestorage.UploadFileResponse
	7, // 8: filestorage.FileStorageService.UploadFileFromUrl:output_type -> filestorage.UploadFileResponse
	6, // 9: filestorage.FileStorageService.GetFileDetail:output_type -> filestorage.FileDetailResponse
	7, // 10: filestorage.FileStorageService.UploadFileChunked:output_type -> filestorage.UploadFileResponse
	7, // 11: filestorage.FileStorageService.CompleteChunkedUpload:output_type -> filestorage.UploadFileResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_filestorage_fileStorage_proto_init() }
func file_proto_filestorage_fileStorage_proto_init() {
	if File_proto_filestorage_fileStorage_proto != nil {
		return
	}
	file_proto_filestorage_fileStorage_proto_msgTypes[0].OneofWrappers = []any{
		(*UploadFileRequest_Metadata)(nil),
		(*UploadFileRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_filestorage_fileStorage_proto_rawDesc), len(file_proto_filestorage_fileStorage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_filestorage_fileStorage_proto_goTypes,
		DependencyIndexes: file_proto_filestorage_fileStorage_proto_depIdxs,
		MessageInfos:      file_proto_filestorage_fileStorage_proto_msgTypes,
	}.Build()
	File_proto_filestorage_fileStorage_proto = out.File
	file_proto_filestorage_fileStorage_proto_goTypes = nil
	file_proto_filestorage_fileStorage_proto_depIdxs = nil
}
