spring:
  datasource:
    username: root
    password: password
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: jdbc:mysql://localhost:3306/gulimall?useUnicode=true&characterEncoding=utf-8&useSSL=false
  rabbitmq:
    port: 5672
    host: 192.168.56.129
  redis:
    host: localhost
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT 中 AES 加密字段解密用的密钥，必须与授权服务器保持一致
AES:
  key: yangzhixuan94416
encrypt:
  key-store:
    location: classpath:/xz.keystore
    secret: xiaozuokeystore
    alias: xzkey
    password: xiaozuo
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone: http://admin:admin@localhost:9000/eureka/